#! /bin/bash

sudo cp ./pharo /usr/local/bin
sudo cp ./pharo-sh /usr/local/bin
sudo cp ./pharo-legacy /usr/local/bin
sudo cp ./phget /usr/local/bin
sudo cp ./phmv /usr/local/bin
sudo cp ./phconfig /usr/local/bin