#! /bin/bash

set -e

default_config_file="config.st"

image="$1"
dest_dir="`dirname $1`"

if [ ! -z "$2" ]; then
	config_file="$2"
else
	config_file="$default_config_file"
fi

if [ -z "$image" ]; then
	echo "Usage: $0 /path/to/image-name [config.st]"
	exit 1
fi

if [ ! -f $dest_dir/$config_file ]; then 
	echo "No $config_file file in $dest_dir"
	exit 1
fi 

echo "Running contents of $dest_dir/$config_file into $image"
pharo-sh $image --no-default-preferences st --save "$config_file"