#!/bin/bash

old_name=$1
new_name=$2

function usage {
	echo "Usage: $0 old-name new-name"
	exit $1
}

if [ "$old_name" == ""  -o "$new_name" == "" ]; then
	usage 1
fi

if [ -d $new_name ]; then
	mv $new_name $new_name~
fi

mv $old_name $new_name
mv $new_name/$old_name.image $new_name/$new_name.image 
mv $new_name/$old_name.changes $new_name/$new_name.changes